common: &default_settings
  license_key: '4ad1cc8015075254b3652effc79c73ad817650f2'
  app_name: My Application
  monitor_mode: true
  developer_mode: false
  log_level: info
  ssl: false
  apdex_t: 0.5
  capture_params: false
  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
  error_collector:
    enabled: true
    capture_source: true    
    ignore_errors: "NoMethodError"

development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true
  log_level: debug

test:
  <<: *default_settings
  monitor_mode: true
  app_name: My Application (Test)
  log_level: debug

production:
  <<: *default_settings
  monitor_mode: true

staging:
  <<: *default_settings
  monitor_mode: true
  app_name: My Application (Staging)